-- Table: area
DROP TABLE public_groups;

CREATE TABLE public_groups
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    type integer  DEFAULT 0 ,
    callsign character varying COLLATE pg_catalog."default",
    allow_cpuid character varying COLLATE pg_catalog."default",
    ower_id   integer DEFAULT 0 ,
    devlist  integer[],
	status       integer DEFAULT 0 ,
    create_time timestamp without time zone,
    update_time timestamp without time zone,
    note character varying COLLATE pg_catalog."default",
    CONSTRAINT public_groups_pkey PRIMARY KEY (id)，
    CONSTRAINT name UNIQUE (name)

   
)

TABLESPACE pg_default;

ALTER TABLE public_groupss
    OWNER to postgres;



DROP TABLE servers;

CREATE TABLE servers
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",  
    cpu_type character varying COLLATE pg_catalog."default",
    mem_size character varying COLLATE pg_catalog."default",
    input_rate integer  DEFAULT 0 ,
    output_rate integer  DEFAULT 0 ,
    netcard character varying COLLATE pg_catalog."default",
    ip_type   integer DEFAULT 0 , 
    ip_addr  character varying COLLATE pg_catalog."default",
    dns_name  character varying COLLATE pg_catalog."default",   
    server_type integer  DEFAULT 0 ,
    group_list integer[],
    ower_id   integer DEFAULT 0 , 
    ower_callsign  character  varying COLLATE pg_catalog."default", 
    is_online     boolean DEFAULT false ,
	status       integer DEFAULT 0 ,
    create_time timestamp without time zone,
    update_time timestamp without time zone,
    note character varying COLLATE pg_catalog."default",
    CONSTRAINT servers_pkey PRIMARY KEY (id)

   
)

TABLESPACE pg_default;

ALTER TABLE servers
    OWNER to postgres;

