- Table: operator_log

-- DROP TABLE operator_log;

CREATE TABLE operator_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "timestamp" timestamp without time zone,
    content character varying COLLATE pg_catalog."default",
    event_type character varying COLLATE pg_catalog."default",
    operator character varying COLLATE pg_catalog."default",
    operator_id integer DEFAULT 0
)

TABLESPACE pg_default;

ALTER TABLE operator_log
    OWNER to postgres;





    CREATE TABLE operator_log
(
      id serial  PRIMARY KEY  ,
    "timestamp" timestamp without time zone,
    content character varying COLLATE pg_catalog."default",
    event_type character varying COLLATE pg_catalog."default",
    operator character varying COLLATE pg_catalog."default",
    operator_id integer DEFAULT 0
)

TABLESPACE pg_default;

ALTER TABLE operator_log
    OWNER to postgres;