-- Table: employee

-- DROP TABLE employee;

CREATE TABLE users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    callsign character varying COLLATE pg_catalog."default" NOT NULL,
    gird character varying COLLATE pg_catalog."default" NOT NULL,
    phone character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    birthday date,
    sex smallint,
    avatar character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    roles character varying[] COLLATE pg_catalog."default",   
    introduction character varying COLLATE pg_catalog."default",  
    alarm_msg boolean DEFAULT false,
    status integer DEFAULT 1,
     update_time timestamp without time zone DEFAULT now(),
    last_login_time timestamp without time zone,
    login_err_times integer,
    create_time timestamp without time zone DEFAULT now(),
    openid character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    nickname character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    pid character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    last_login_ip character varying COLLATE pg_catalog."default" DEFAULT '0.0.0.0'::character varying,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT phone UNIQUE (phone),
    CONSTRAINT callsign UNIQUE (callsign)
)
    
TABLESPACE pg_default;

ALTER TABLE users
    OWNER to postgres;




    
CREATE TABLE employee 
(
   id serial  ,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    phone character  varying COLLATE pg_catalog."default" primary key,
    password character varying COLLATE pg_catalog."default",
    birthday date,
    sex smallint,
    avatar character varying COLLATE pg_catalog."default",
    roles character varying[] COLLATE pg_catalog."default",
    update_time timestamp without time zone DEFAULT now(),
    introduction character varying COLLATE pg_catalog."default",
    job_time date,
    area integer[],
    current_area integer,
    schname character varying COLLATE pg_catalog."default",
    alarm_msg boolean DEFAULT false,
    status integer DEFAULT 1,
    last_login_time timestamp without time zone,
    login_err_times integer,
    create_time timestamp without time zone DEFAULT now(),
    openid character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    nickname character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    pid character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    last_login_ip character varying COLLATE pg_catalog."default" DEFAULT '0.0.0.0'::character varying


)
    
TABLESPACE pg_default;